#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 30 11:15:18 2020

@author: samirothstein
"""

import numpy as np
import matplotlib.pyplot as plt
import statistics
import scipy.signal as sig

#functions
def update_system(acc,theta,vel,l):
    accNext = -386.1*np.sin(theta)/l
#    gravity in in/s^2
    dt = .002 
#    time step in s
    velNext = vel+(accNext*dt)
#    in/s
    thetaNext = theta+(velNext*dt)
#    in.
    return thetaNext,velNext,accNext

def period(theta):
#finding the period based on the theta
    theta_pks, _ = sig.find_peaks(theta)
    time_val = time[theta_pks]
    period_L = []
    for i in range(len(time_val)-1):
        interval = time_val[i+1]-time_val[i]
        period_L.append(interval)
#    print(period_L)
    avg_period = statistics.mean(period_L)
    return avg_period,period_L

def graph_time(acceleration,velocity,theta,time):

    plt.subplot(4,1,1)
    plt.plot(time,theta)
    plt.xlabel('Time (s)')
    plt.ylabel('Theta (rad)')
    plt.title('Theta vs.Time')
    plt.show()

    plt.subplot(4,1,2)
    plt.plot(time,vel)
    plt.xlabel('Time (s)')
    plt.ylabel('Velocity (in/s)')
    plt.title('Velocity vs.Time')
    plt.show()

    plt.subplot(4,1,3)
    plt.plot(time,acceleration)
    plt.xlabel('Time (s)')
    plt.ylabel('Acceleration (in/s^2)')
    plt.title('Acceleration vs.Time')
    plt.show()

def graph_period(length,avgT):
    plt.plot(length,avgT)
    plt.ylabel('Period (s)')
    plt.xlabel('Length (in.)')
    plt.title('Length vs. Period')
    plt.show()



#initial conditions
vel = np.array([0])
acc = np.array([0])
theta = [np.pi/2]
time = np.linspace(0,20,num=10000)
length = [8.75,11,13,15,17]
avgT=np.array([])



i = 1
for x in length:
    while i < len(time):
        thetaNext,velNext, accNext = update_system(acc[i-1],theta[i-1],vel[i-1],x)
        theta = np.append(theta, thetaNext)
        vel = np.append(vel, velNext)
        acc = np.append(acc, accNext)
        i +=1

    avg_period,period_L = period(acc)
    avgT = np.append(avgT,avg_period)
    graph_time(acc,vel,theta,time)
graph_period(length,avgT)

